export enum SCREENS {
  APP_STACK = 'APP_STACK',
  BOTTOM_TABS = 'BOTTOM_TABS',
  // auth
  SIGN_UP = 'SIGN_UP',
  SING_IN = 'SING_IN',
  PERSONAL_INFO = 'PERSONAL_INFO',
  LANDING = 'LANDING',

  HOME = 'HOME',
  PROFILE = 'PROFILE',
  DISCOVER = 'DISCOVER',
  // settings
  PRIVACY_POLICY = 'PRIVACY_POLICY',
}
